# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wk/w/pinentry-qt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wk/w/pinentry-qt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/wk/w/pinentry-qt/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wk/w/pinentry-qt/CMakeFiles /home/wk/w/pinentry-qt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wk/w/pinentry-qt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pinentry-qt

# Build rule for target.
pinentry-qt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pinentry-qt
.PHONY : pinentry-qt

# fast build rule for target.
pinentry-qt/fast:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/build
.PHONY : pinentry-qt/fast

assuan-buffer.o: assuan-buffer.c.o
.PHONY : assuan-buffer.o

# target to build an object file
assuan-buffer.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.c.o
.PHONY : assuan-buffer.c.o

assuan-buffer.i: assuan-buffer.c.i
.PHONY : assuan-buffer.i

# target to preprocess a source file
assuan-buffer.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.c.i
.PHONY : assuan-buffer.c.i

assuan-buffer.s: assuan-buffer.c.s
.PHONY : assuan-buffer.s

# target to generate assembly for a file
assuan-buffer.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.c.s
.PHONY : assuan-buffer.c.s

assuan-errors.o: assuan-errors.c.o
.PHONY : assuan-errors.o

# target to build an object file
assuan-errors.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.c.o
.PHONY : assuan-errors.c.o

assuan-errors.i: assuan-errors.c.i
.PHONY : assuan-errors.i

# target to preprocess a source file
assuan-errors.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.c.i
.PHONY : assuan-errors.c.i

assuan-errors.s: assuan-errors.c.s
.PHONY : assuan-errors.s

# target to generate assembly for a file
assuan-errors.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.c.s
.PHONY : assuan-errors.c.s

assuan-handler.o: assuan-handler.c.o
.PHONY : assuan-handler.o

# target to build an object file
assuan-handler.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.c.o
.PHONY : assuan-handler.c.o

assuan-handler.i: assuan-handler.c.i
.PHONY : assuan-handler.i

# target to preprocess a source file
assuan-handler.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.c.i
.PHONY : assuan-handler.c.i

assuan-handler.s: assuan-handler.c.s
.PHONY : assuan-handler.s

# target to generate assembly for a file
assuan-handler.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.c.s
.PHONY : assuan-handler.c.s

assuan-listen.o: assuan-listen.c.o
.PHONY : assuan-listen.o

# target to build an object file
assuan-listen.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.c.o
.PHONY : assuan-listen.c.o

assuan-listen.i: assuan-listen.c.i
.PHONY : assuan-listen.i

# target to preprocess a source file
assuan-listen.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.c.i
.PHONY : assuan-listen.c.i

assuan-listen.s: assuan-listen.c.s
.PHONY : assuan-listen.s

# target to generate assembly for a file
assuan-listen.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.c.s
.PHONY : assuan-listen.c.s

assuan-pipe-server.o: assuan-pipe-server.c.o
.PHONY : assuan-pipe-server.o

# target to build an object file
assuan-pipe-server.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.c.o
.PHONY : assuan-pipe-server.c.o

assuan-pipe-server.i: assuan-pipe-server.c.i
.PHONY : assuan-pipe-server.i

# target to preprocess a source file
assuan-pipe-server.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.c.i
.PHONY : assuan-pipe-server.c.i

assuan-pipe-server.s: assuan-pipe-server.c.s
.PHONY : assuan-pipe-server.s

# target to generate assembly for a file
assuan-pipe-server.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.c.s
.PHONY : assuan-pipe-server.c.s

assuan-util.o: assuan-util.c.o
.PHONY : assuan-util.o

# target to build an object file
assuan-util.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.c.o
.PHONY : assuan-util.c.o

assuan-util.i: assuan-util.c.i
.PHONY : assuan-util.i

# target to preprocess a source file
assuan-util.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.c.i
.PHONY : assuan-util.c.i

assuan-util.s: assuan-util.c.s
.PHONY : assuan-util.s

# target to generate assembly for a file
assuan-util.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.c.s
.PHONY : assuan-util.c.s

getopt.o: getopt.c.o
.PHONY : getopt.o

# target to build an object file
getopt.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/getopt.c.o
.PHONY : getopt.c.o

getopt.i: getopt.c.i
.PHONY : getopt.i

# target to preprocess a source file
getopt.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/getopt.c.i
.PHONY : getopt.c.i

getopt.s: getopt.c.s
.PHONY : getopt.s

# target to generate assembly for a file
getopt.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/getopt.c.s
.PHONY : getopt.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.cpp.s
.PHONY : main.cpp.s

pinentry.o: pinentry.c.o
.PHONY : pinentry.o

# target to build an object file
pinentry.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.c.o
.PHONY : pinentry.c.o

pinentry.i: pinentry.c.i
.PHONY : pinentry.i

# target to preprocess a source file
pinentry.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.c.i
.PHONY : pinentry.c.i

pinentry.s: pinentry.c.s
.PHONY : pinentry.s

# target to generate assembly for a file
pinentry.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.c.s
.PHONY : pinentry.c.s

pinentrydialog.o: pinentrydialog.cpp.o
.PHONY : pinentrydialog.o

# target to build an object file
pinentrydialog.cpp.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.cpp.o
.PHONY : pinentrydialog.cpp.o

pinentrydialog.i: pinentrydialog.cpp.i
.PHONY : pinentrydialog.i

# target to preprocess a source file
pinentrydialog.cpp.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.cpp.i
.PHONY : pinentrydialog.cpp.i

pinentrydialog.s: pinentrydialog.cpp.s
.PHONY : pinentrydialog.s

# target to generate assembly for a file
pinentrydialog.cpp.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.cpp.s
.PHONY : pinentrydialog.cpp.s

qrc_pinentry.o: qrc_pinentry.cpp.o
.PHONY : qrc_pinentry.o

# target to build an object file
qrc_pinentry.cpp.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.cpp.o
.PHONY : qrc_pinentry.cpp.o

qrc_pinentry.i: qrc_pinentry.cpp.i
.PHONY : qrc_pinentry.i

# target to preprocess a source file
qrc_pinentry.cpp.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.cpp.i
.PHONY : qrc_pinentry.cpp.i

qrc_pinentry.s: qrc_pinentry.cpp.s
.PHONY : qrc_pinentry.s

# target to generate assembly for a file
qrc_pinentry.cpp.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.cpp.s
.PHONY : qrc_pinentry.cpp.s

secmem-util.o: secmem-util.c.o
.PHONY : secmem-util.o

# target to build an object file
secmem-util.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.c.o
.PHONY : secmem-util.c.o

secmem-util.i: secmem-util.c.i
.PHONY : secmem-util.i

# target to preprocess a source file
secmem-util.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.c.i
.PHONY : secmem-util.c.i

secmem-util.s: secmem-util.c.s
.PHONY : secmem-util.s

# target to generate assembly for a file
secmem-util.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.c.s
.PHONY : secmem-util.c.s

secmem.o: secmem.c.o
.PHONY : secmem.o

# target to build an object file
secmem.c.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.c.o
.PHONY : secmem.c.o

secmem.i: secmem.c.i
.PHONY : secmem.i

# target to preprocess a source file
secmem.c.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.c.i
.PHONY : secmem.c.i

secmem.s: secmem.c.s
.PHONY : secmem.s

# target to generate assembly for a file
secmem.c.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.c.s
.PHONY : secmem.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... pinentry-qt"
	@echo "... rebuild_cache"
	@echo "... assuan-buffer.o"
	@echo "... assuan-buffer.i"
	@echo "... assuan-buffer.s"
	@echo "... assuan-errors.o"
	@echo "... assuan-errors.i"
	@echo "... assuan-errors.s"
	@echo "... assuan-handler.o"
	@echo "... assuan-handler.i"
	@echo "... assuan-handler.s"
	@echo "... assuan-listen.o"
	@echo "... assuan-listen.i"
	@echo "... assuan-listen.s"
	@echo "... assuan-pipe-server.o"
	@echo "... assuan-pipe-server.i"
	@echo "... assuan-pipe-server.s"
	@echo "... assuan-util.o"
	@echo "... assuan-util.i"
	@echo "... assuan-util.s"
	@echo "... getopt.o"
	@echo "... getopt.i"
	@echo "... getopt.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pinentry.o"
	@echo "... pinentry.i"
	@echo "... pinentry.s"
	@echo "... pinentrydialog.o"
	@echo "... pinentrydialog.i"
	@echo "... pinentrydialog.s"
	@echo "... qrc_pinentry.o"
	@echo "... qrc_pinentry.i"
	@echo "... qrc_pinentry.s"
	@echo "... secmem-util.o"
	@echo "... secmem-util.i"
	@echo "... secmem-util.s"
	@echo "... secmem.o"
	@echo "... secmem.i"
	@echo "... secmem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

