# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcus/g10/projects/komo3/cmake/pinentry-qt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcus/g10/projects/komo3/cmake/pinentry-qt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcus/g10/projects/komo3/cmake/pinentry-qt/CMakeFiles /home/marcus/g10/projects/komo3/cmake/pinentry-qt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcus/g10/projects/komo3/cmake/pinentry-qt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pinentry-qt

# Build rule for target.
pinentry-qt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pinentry-qt
.PHONY : pinentry-qt

# fast build rule for target.
pinentry-qt/fast:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/build
.PHONY : pinentry-qt/fast

# target to build an object file
assuan-buffer.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.o
.PHONY : assuan-buffer.o

# target to preprocess a source file
assuan-buffer.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.i
.PHONY : assuan-buffer.i

# target to generate assembly for a file
assuan-buffer.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-buffer.s
.PHONY : assuan-buffer.s

# target to build an object file
assuan-errors.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.o
.PHONY : assuan-errors.o

# target to preprocess a source file
assuan-errors.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.i
.PHONY : assuan-errors.i

# target to generate assembly for a file
assuan-errors.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-errors.s
.PHONY : assuan-errors.s

# target to build an object file
assuan-handler.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.o
.PHONY : assuan-handler.o

# target to preprocess a source file
assuan-handler.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.i
.PHONY : assuan-handler.i

# target to generate assembly for a file
assuan-handler.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-handler.s
.PHONY : assuan-handler.s

# target to build an object file
assuan-listen.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.o
.PHONY : assuan-listen.o

# target to preprocess a source file
assuan-listen.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.i
.PHONY : assuan-listen.i

# target to generate assembly for a file
assuan-listen.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-listen.s
.PHONY : assuan-listen.s

# target to build an object file
assuan-pipe-server.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.o
.PHONY : assuan-pipe-server.o

# target to preprocess a source file
assuan-pipe-server.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.i
.PHONY : assuan-pipe-server.i

# target to generate assembly for a file
assuan-pipe-server.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-pipe-server.s
.PHONY : assuan-pipe-server.s

# target to build an object file
assuan-util.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.o
.PHONY : assuan-util.o

# target to preprocess a source file
assuan-util.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.i
.PHONY : assuan-util.i

# target to generate assembly for a file
assuan-util.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/assuan-util.s
.PHONY : assuan-util.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/main.s
.PHONY : main.s

# target to build an object file
pinentry.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.o
.PHONY : pinentry.o

# target to preprocess a source file
pinentry.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.i
.PHONY : pinentry.i

# target to generate assembly for a file
pinentry.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentry.s
.PHONY : pinentry.s

# target to build an object file
pinentrydialog.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.o
.PHONY : pinentrydialog.o

# target to preprocess a source file
pinentrydialog.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.i
.PHONY : pinentrydialog.i

# target to generate assembly for a file
pinentrydialog.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/pinentrydialog.s
.PHONY : pinentrydialog.s

# target to build an object file
qrc_pinentry.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.o
.PHONY : qrc_pinentry.o

# target to preprocess a source file
qrc_pinentry.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.i
.PHONY : qrc_pinentry.i

# target to generate assembly for a file
qrc_pinentry.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/qrc_pinentry.s
.PHONY : qrc_pinentry.s

# target to build an object file
secmem-util.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.o
.PHONY : secmem-util.o

# target to preprocess a source file
secmem-util.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.i
.PHONY : secmem-util.i

# target to generate assembly for a file
secmem-util.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem-util.s
.PHONY : secmem-util.s

# target to build an object file
secmem.o:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.o
.PHONY : secmem.o

# target to preprocess a source file
secmem.i:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.i
.PHONY : secmem.i

# target to generate assembly for a file
secmem.s:
	$(MAKE) -f CMakeFiles/pinentry-qt.dir/build.make CMakeFiles/pinentry-qt.dir/secmem.s
.PHONY : secmem.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... pinentry-qt"
	@echo "... rebuild_cache"
	@echo "... assuan-buffer.o"
	@echo "... assuan-buffer.i"
	@echo "... assuan-buffer.s"
	@echo "... assuan-errors.o"
	@echo "... assuan-errors.i"
	@echo "... assuan-errors.s"
	@echo "... assuan-handler.o"
	@echo "... assuan-handler.i"
	@echo "... assuan-handler.s"
	@echo "... assuan-listen.o"
	@echo "... assuan-listen.i"
	@echo "... assuan-listen.s"
	@echo "... assuan-pipe-server.o"
	@echo "... assuan-pipe-server.i"
	@echo "... assuan-pipe-server.s"
	@echo "... assuan-util.o"
	@echo "... assuan-util.i"
	@echo "... assuan-util.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pinentry.o"
	@echo "... pinentry.i"
	@echo "... pinentry.s"
	@echo "... pinentrydialog.o"
	@echo "... pinentrydialog.i"
	@echo "... pinentrydialog.s"
	@echo "... qrc_pinentry.o"
	@echo "... qrc_pinentry.i"
	@echo "... qrc_pinentry.s"
	@echo "... secmem-util.o"
	@echo "... secmem-util.i"
	@echo "... secmem-util.s"
	@echo "... secmem.o"
	@echo "... secmem.i"
	@echo "... secmem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

